version: "3.9"

services:
  web:
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FRONTEND_SERVER=frontend:3000
      - BACKEND_SERVER=backend:4000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

  frontend:
    build: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: backend
    volumes:
      - './backend:/app/code'
    ports:
      - 4001:4000
    environment:
      DATABASE_NAME: shortly
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
